# Dependencies
markdown:         kramdown
pygments:         true
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            ars.me
tagline:          My personal website
url:
paginate:         1
author:
  name:           A. R. Shajii
  url:            ars.me
  email:          ars@ars.me
comments:
  provider: disqus
  disqus:
    short_name: arsme

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/arshajii/arshajii.github.io
